# -*- coding: utf-8 -*-
"""calculadora simple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbPfc4dwFPhpo2snkDC_y7kLLyumGtEC
"""

import streamlit as st

## Titulo de la applicacion
st.title("Calculadora hora")

num1 = st.number_input("Ingrese el primer número", value=0)
num2 = st.number_input("Ingrese el segundo número", value=0)

if st.button("Calcular"):
    resultado = num1 + num2
    st.success(f"El resultado de la suma es: {resultado}")